{% set name = "pyramid_beaker" %}
{% set version = "0.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 77dc658c2c84c8c384b6c07f60dd9d2ccaa30df97a147c790db43636f1e8d441

build:
  noarch: python
  number: 1
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - pyramid
    - beaker

test:
  requires:
    - python {{ python_min }}
  imports:
    - {{ name }}

about:
  home: https://pypi.org/project/{{ name }}/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: 'A session factory for the Pyramid web framework backed by the Beaker sessioning system.'
  description: 'A session factory for the Pyramid web framework backed by the Beaker sessioning system.'
  dev_url: https://github.com/Pylons/pyramid_beaker
  doc_url: https://docs.pylonsproject.org/en/latest/

extra:
  recipe-maintainers:
    - ChrisBarker-NOAA
    - daf
